clear all;close all;clc;
f1=@(x)2.*x.^4+3.*x.^2-4.*x+5;
f2=@(x)x.^6+3.*x.^4-2.*x.^3+x.^2-x-7;
figure(1);
t=-1:0.001:1;
plot(t,f1(t));
title('f1');
figure(2);
plot(t,f2(t));
title('f2');
a=0;
b=1;
TOL=5e-6;
epsilon=TOL;
[x_min1,y_min1] =GoldenSection(f1,a,b,TOL,epsilon);
[x_min2,y_min2] =GoldenSection(f2,a,b,TOL,epsilon);
[X1,FVAL1,EXITFLAG1] = fminbnd(f1,a,b);
[X2,FVAL2,EXITFLAG2] = fminbnd(f2,a,b);
disp('==============================');
disp('For function (a):');
fprintf('The minimum point found by golden section is x=%10.9f,y=%10.9f\n',x_min1,y_min1);
fprintf('The minimum point found by fminbnd is x=%10.9f,y=%10.9f\n',X1,FVAL1);
disp(['The exit flag for fminbnd is ' num2str(EXITFLAG1)]);
disp('==============================');
disp('For function (b):');
fprintf('The minimum point found by golden section is x=%10.9f,y=%10.9f\n',x_min2,y_min2);
fprintf('The minimum point found by fminbnd is x=%10.9f,y=%10.9f\n',X2,FVAL2);
disp(['The exit flag for fminbnd is ' num2str(EXITFLAG2)]);
